// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/project"
	"github.com/Wei-Shaw/sub2api/ent/projectprofile"
	"github.com/Wei-Shaw/sub2api/ent/projectprofilebinding"
)

// ProjectProfileUpdate is the builder for updating ProjectProfile entities.
type ProjectProfileUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectProfileMutation
}

// Where appends a list predicates to the ProjectProfileUpdate builder.
func (_u *ProjectProfileUpdate) Where(ps ...predicate.ProjectProfile) *ProjectProfileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProjectProfileUpdate) SetUpdatedAt(v time.Time) *ProjectProfileUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ProjectProfileUpdate) SetDeletedAt(v time.Time) *ProjectProfileUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ProjectProfileUpdate) SetNillableDeletedAt(v *time.Time) *ProjectProfileUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ProjectProfileUpdate) ClearDeletedAt() *ProjectProfileUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *ProjectProfileUpdate) SetProjectID(v int64) *ProjectProfileUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *ProjectProfileUpdate) SetNillableProjectID(v *int64) *ProjectProfileUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ProjectProfileUpdate) SetName(v string) *ProjectProfileUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProjectProfileUpdate) SetNillableName(v *string) *ProjectProfileUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ProjectProfileUpdate) SetDescription(v string) *ProjectProfileUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ProjectProfileUpdate) SetNillableDescription(v *string) *ProjectProfileUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ProjectProfileUpdate) ClearDescription() *ProjectProfileUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetMode sets the "mode" field.
func (_u *ProjectProfileUpdate) SetMode(v string) *ProjectProfileUpdate {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *ProjectProfileUpdate) SetNillableMode(v *string) *ProjectProfileUpdate {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *ProjectProfileUpdate) SetIsActive(v bool) *ProjectProfileUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *ProjectProfileUpdate) SetNillableIsActive(v *bool) *ProjectProfileUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *ProjectProfileUpdate) SetProject(v *Project) *ProjectProfileUpdate {
	return _u.SetProjectID(v.ID)
}

// AddBindingIDs adds the "bindings" edge to the ProjectProfileBinding entity by IDs.
func (_u *ProjectProfileUpdate) AddBindingIDs(ids ...int64) *ProjectProfileUpdate {
	_u.mutation.AddBindingIDs(ids...)
	return _u
}

// AddBindings adds the "bindings" edges to the ProjectProfileBinding entity.
func (_u *ProjectProfileUpdate) AddBindings(v ...*ProjectProfileBinding) *ProjectProfileUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBindingIDs(ids...)
}

// Mutation returns the ProjectProfileMutation object of the builder.
func (_u *ProjectProfileUpdate) Mutation() *ProjectProfileMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *ProjectProfileUpdate) ClearProject() *ProjectProfileUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearBindings clears all "bindings" edges to the ProjectProfileBinding entity.
func (_u *ProjectProfileUpdate) ClearBindings() *ProjectProfileUpdate {
	_u.mutation.ClearBindings()
	return _u
}

// RemoveBindingIDs removes the "bindings" edge to ProjectProfileBinding entities by IDs.
func (_u *ProjectProfileUpdate) RemoveBindingIDs(ids ...int64) *ProjectProfileUpdate {
	_u.mutation.RemoveBindingIDs(ids...)
	return _u
}

// RemoveBindings removes "bindings" edges to ProjectProfileBinding entities.
func (_u *ProjectProfileUpdate) RemoveBindings(v ...*ProjectProfileBinding) *ProjectProfileUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBindingIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProjectProfileUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProjectProfileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectProfileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProjectProfileUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if projectprofile.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized projectprofile.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := projectprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectProfileUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := projectprofile.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProjectProfile.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mode(); ok {
		if err := projectprofile.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "ProjectProfile.mode": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectProfile.project"`)
	}
	return nil
}

func (_u *ProjectProfileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(projectprofile.Table, projectprofile.Columns, sqlgraph.NewFieldSpec(projectprofile.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(projectprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(projectprofile.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(projectprofile.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(projectprofile.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(projectprofile.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(projectprofile.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(projectprofile.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(projectprofile.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectprofile.ProjectTable,
			Columns: []string{projectprofile.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectprofile.ProjectTable,
			Columns: []string{projectprofile.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   projectprofile.BindingsTable,
			Columns: []string{projectprofile.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectprofilebinding.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBindingsIDs(); len(nodes) > 0 && !_u.mutation.BindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   projectprofile.BindingsTable,
			Columns: []string{projectprofile.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectprofilebinding.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   projectprofile.BindingsTable,
			Columns: []string{projectprofile.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectprofilebinding.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projectprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProjectProfileUpdateOne is the builder for updating a single ProjectProfile entity.
type ProjectProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectProfileMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProjectProfileUpdateOne) SetUpdatedAt(v time.Time) *ProjectProfileUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ProjectProfileUpdateOne) SetDeletedAt(v time.Time) *ProjectProfileUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ProjectProfileUpdateOne) SetNillableDeletedAt(v *time.Time) *ProjectProfileUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ProjectProfileUpdateOne) ClearDeletedAt() *ProjectProfileUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *ProjectProfileUpdateOne) SetProjectID(v int64) *ProjectProfileUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *ProjectProfileUpdateOne) SetNillableProjectID(v *int64) *ProjectProfileUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ProjectProfileUpdateOne) SetName(v string) *ProjectProfileUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProjectProfileUpdateOne) SetNillableName(v *string) *ProjectProfileUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ProjectProfileUpdateOne) SetDescription(v string) *ProjectProfileUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ProjectProfileUpdateOne) SetNillableDescription(v *string) *ProjectProfileUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ProjectProfileUpdateOne) ClearDescription() *ProjectProfileUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetMode sets the "mode" field.
func (_u *ProjectProfileUpdateOne) SetMode(v string) *ProjectProfileUpdateOne {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *ProjectProfileUpdateOne) SetNillableMode(v *string) *ProjectProfileUpdateOne {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *ProjectProfileUpdateOne) SetIsActive(v bool) *ProjectProfileUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *ProjectProfileUpdateOne) SetNillableIsActive(v *bool) *ProjectProfileUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *ProjectProfileUpdateOne) SetProject(v *Project) *ProjectProfileUpdateOne {
	return _u.SetProjectID(v.ID)
}

// AddBindingIDs adds the "bindings" edge to the ProjectProfileBinding entity by IDs.
func (_u *ProjectProfileUpdateOne) AddBindingIDs(ids ...int64) *ProjectProfileUpdateOne {
	_u.mutation.AddBindingIDs(ids...)
	return _u
}

// AddBindings adds the "bindings" edges to the ProjectProfileBinding entity.
func (_u *ProjectProfileUpdateOne) AddBindings(v ...*ProjectProfileBinding) *ProjectProfileUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBindingIDs(ids...)
}

// Mutation returns the ProjectProfileMutation object of the builder.
func (_u *ProjectProfileUpdateOne) Mutation() *ProjectProfileMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *ProjectProfileUpdateOne) ClearProject() *ProjectProfileUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearBindings clears all "bindings" edges to the ProjectProfileBinding entity.
func (_u *ProjectProfileUpdateOne) ClearBindings() *ProjectProfileUpdateOne {
	_u.mutation.ClearBindings()
	return _u
}

// RemoveBindingIDs removes the "bindings" edge to ProjectProfileBinding entities by IDs.
func (_u *ProjectProfileUpdateOne) RemoveBindingIDs(ids ...int64) *ProjectProfileUpdateOne {
	_u.mutation.RemoveBindingIDs(ids...)
	return _u
}

// RemoveBindings removes "bindings" edges to ProjectProfileBinding entities.
func (_u *ProjectProfileUpdateOne) RemoveBindings(v ...*ProjectProfileBinding) *ProjectProfileUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBindingIDs(ids...)
}

// Where appends a list predicates to the ProjectProfileUpdate builder.
func (_u *ProjectProfileUpdateOne) Where(ps ...predicate.ProjectProfile) *ProjectProfileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProjectProfileUpdateOne) Select(field string, fields ...string) *ProjectProfileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProjectProfile entity.
func (_u *ProjectProfileUpdateOne) Save(ctx context.Context) (*ProjectProfile, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectProfileUpdateOne) SaveX(ctx context.Context) *ProjectProfile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProjectProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectProfileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProjectProfileUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if projectprofile.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized projectprofile.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := projectprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectProfileUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := projectprofile.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProjectProfile.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mode(); ok {
		if err := projectprofile.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "ProjectProfile.mode": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectProfile.project"`)
	}
	return nil
}

func (_u *ProjectProfileUpdateOne) sqlSave(ctx context.Context) (_node *ProjectProfile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(projectprofile.Table, projectprofile.Columns, sqlgraph.NewFieldSpec(projectprofile.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProjectProfile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, projectprofile.FieldID)
		for _, f := range fields {
			if !projectprofile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != projectprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(projectprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(projectprofile.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(projectprofile.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(projectprofile.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(projectprofile.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(projectprofile.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(projectprofile.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(projectprofile.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectprofile.ProjectTable,
			Columns: []string{projectprofile.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectprofile.ProjectTable,
			Columns: []string{projectprofile.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   projectprofile.BindingsTable,
			Columns: []string{projectprofile.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectprofilebinding.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBindingsIDs(); len(nodes) > 0 && !_u.mutation.BindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   projectprofile.BindingsTable,
			Columns: []string{projectprofile.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectprofilebinding.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   projectprofile.BindingsTable,
			Columns: []string{projectprofile.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectprofilebinding.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProjectProfile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projectprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
