// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/project"
	"github.com/Wei-Shaw/sub2api/ent/projectprofile"
	"github.com/Wei-Shaw/sub2api/ent/projectprofilebinding"
)

// ProjectProfileQuery is the builder for querying ProjectProfile entities.
type ProjectProfileQuery struct {
	config
	ctx          *QueryContext
	order        []projectprofile.OrderOption
	inters       []Interceptor
	predicates   []predicate.ProjectProfile
	withProject  *ProjectQuery
	withBindings *ProjectProfileBindingQuery
	modifiers    []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProjectProfileQuery builder.
func (_q *ProjectProfileQuery) Where(ps ...predicate.ProjectProfile) *ProjectProfileQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ProjectProfileQuery) Limit(limit int) *ProjectProfileQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ProjectProfileQuery) Offset(offset int) *ProjectProfileQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ProjectProfileQuery) Unique(unique bool) *ProjectProfileQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ProjectProfileQuery) Order(o ...projectprofile.OrderOption) *ProjectProfileQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryProject chains the current query on the "project" edge.
func (_q *ProjectProfileQuery) QueryProject() *ProjectQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(projectprofile.Table, projectprofile.FieldID, selector),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, projectprofile.ProjectTable, projectprofile.ProjectColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBindings chains the current query on the "bindings" edge.
func (_q *ProjectProfileQuery) QueryBindings() *ProjectProfileBindingQuery {
	query := (&ProjectProfileBindingClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(projectprofile.Table, projectprofile.FieldID, selector),
			sqlgraph.To(projectprofilebinding.Table, projectprofilebinding.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, projectprofile.BindingsTable, projectprofile.BindingsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProjectProfile entity from the query.
// Returns a *NotFoundError when no ProjectProfile was found.
func (_q *ProjectProfileQuery) First(ctx context.Context) (*ProjectProfile, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{projectprofile.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ProjectProfileQuery) FirstX(ctx context.Context) *ProjectProfile {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProjectProfile ID from the query.
// Returns a *NotFoundError when no ProjectProfile ID was found.
func (_q *ProjectProfileQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{projectprofile.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ProjectProfileQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProjectProfile entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProjectProfile entity is found.
// Returns a *NotFoundError when no ProjectProfile entities are found.
func (_q *ProjectProfileQuery) Only(ctx context.Context) (*ProjectProfile, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{projectprofile.Label}
	default:
		return nil, &NotSingularError{projectprofile.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ProjectProfileQuery) OnlyX(ctx context.Context) *ProjectProfile {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProjectProfile ID in the query.
// Returns a *NotSingularError when more than one ProjectProfile ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ProjectProfileQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{projectprofile.Label}
	default:
		err = &NotSingularError{projectprofile.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ProjectProfileQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProjectProfiles.
func (_q *ProjectProfileQuery) All(ctx context.Context) ([]*ProjectProfile, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProjectProfile, *ProjectProfileQuery]()
	return withInterceptors[[]*ProjectProfile](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ProjectProfileQuery) AllX(ctx context.Context) []*ProjectProfile {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProjectProfile IDs.
func (_q *ProjectProfileQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(projectprofile.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ProjectProfileQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ProjectProfileQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ProjectProfileQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ProjectProfileQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ProjectProfileQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ProjectProfileQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProjectProfileQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ProjectProfileQuery) Clone() *ProjectProfileQuery {
	if _q == nil {
		return nil
	}
	return &ProjectProfileQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]projectprofile.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.ProjectProfile{}, _q.predicates...),
		withProject:  _q.withProject.Clone(),
		withBindings: _q.withBindings.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithProject tells the query-builder to eager-load the nodes that are connected to
// the "project" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProjectProfileQuery) WithProject(opts ...func(*ProjectQuery)) *ProjectProfileQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProject = query
	return _q
}

// WithBindings tells the query-builder to eager-load the nodes that are connected to
// the "bindings" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProjectProfileQuery) WithBindings(opts ...func(*ProjectProfileBindingQuery)) *ProjectProfileQuery {
	query := (&ProjectProfileBindingClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBindings = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProjectProfile.Query().
//		GroupBy(projectprofile.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ProjectProfileQuery) GroupBy(field string, fields ...string) *ProjectProfileGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProjectProfileGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = projectprofile.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ProjectProfile.Query().
//		Select(projectprofile.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *ProjectProfileQuery) Select(fields ...string) *ProjectProfileSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ProjectProfileSelect{ProjectProfileQuery: _q}
	sbuild.label = projectprofile.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProjectProfileSelect configured with the given aggregations.
func (_q *ProjectProfileQuery) Aggregate(fns ...AggregateFunc) *ProjectProfileSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ProjectProfileQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !projectprofile.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ProjectProfileQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProjectProfile, error) {
	var (
		nodes       = []*ProjectProfile{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withProject != nil,
			_q.withBindings != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProjectProfile).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProjectProfile{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withProject; query != nil {
		if err := _q.loadProject(ctx, query, nodes, nil,
			func(n *ProjectProfile, e *Project) { n.Edges.Project = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withBindings; query != nil {
		if err := _q.loadBindings(ctx, query, nodes,
			func(n *ProjectProfile) { n.Edges.Bindings = []*ProjectProfileBinding{} },
			func(n *ProjectProfile, e *ProjectProfileBinding) { n.Edges.Bindings = append(n.Edges.Bindings, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ProjectProfileQuery) loadProject(ctx context.Context, query *ProjectQuery, nodes []*ProjectProfile, init func(*ProjectProfile), assign func(*ProjectProfile, *Project)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*ProjectProfile)
	for i := range nodes {
		fk := nodes[i].ProjectID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(project.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "project_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ProjectProfileQuery) loadBindings(ctx context.Context, query *ProjectProfileBindingQuery, nodes []*ProjectProfile, init func(*ProjectProfile), assign func(*ProjectProfile, *ProjectProfileBinding)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*ProjectProfile)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(projectprofilebinding.FieldProjectProfileID)
	}
	query.Where(predicate.ProjectProfileBinding(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(projectprofile.BindingsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ProjectProfileID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "project_profile_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ProjectProfileQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ProjectProfileQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(projectprofile.Table, projectprofile.Columns, sqlgraph.NewFieldSpec(projectprofile.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, projectprofile.FieldID)
		for i := range fields {
			if fields[i] != projectprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withProject != nil {
			_spec.Node.AddColumnOnce(projectprofile.FieldProjectID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ProjectProfileQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(projectprofile.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = projectprofile.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *ProjectProfileQuery) ForUpdate(opts ...sql.LockOption) *ProjectProfileQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *ProjectProfileQuery) ForShare(opts ...sql.LockOption) *ProjectProfileQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// ProjectProfileGroupBy is the group-by builder for ProjectProfile entities.
type ProjectProfileGroupBy struct {
	selector
	build *ProjectProfileQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ProjectProfileGroupBy) Aggregate(fns ...AggregateFunc) *ProjectProfileGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ProjectProfileGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProjectProfileQuery, *ProjectProfileGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ProjectProfileGroupBy) sqlScan(ctx context.Context, root *ProjectProfileQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProjectProfileSelect is the builder for selecting fields of ProjectProfile entities.
type ProjectProfileSelect struct {
	*ProjectProfileQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ProjectProfileSelect) Aggregate(fns ...AggregateFunc) *ProjectProfileSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ProjectProfileSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProjectProfileQuery, *ProjectProfileSelect](ctx, _s.ProjectProfileQuery, _s, _s.inters, v)
}

func (_s *ProjectProfileSelect) sqlScan(ctx context.Context, root *ProjectProfileQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
