// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/projectprofile"
	"github.com/Wei-Shaw/sub2api/ent/projectprofilebinding"
)

// ProjectProfileBindingCreate is the builder for creating a ProjectProfileBinding entity.
type ProjectProfileBindingCreate struct {
	config
	mutation *ProjectProfileBindingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProjectProfileID sets the "project_profile_id" field.
func (_c *ProjectProfileBindingCreate) SetProjectProfileID(v int64) *ProjectProfileBindingCreate {
	_c.mutation.SetProjectProfileID(v)
	return _c
}

// SetResourceType sets the "resource_type" field.
func (_c *ProjectProfileBindingCreate) SetResourceType(v string) *ProjectProfileBindingCreate {
	_c.mutation.SetResourceType(v)
	return _c
}

// SetResourceID sets the "resource_id" field.
func (_c *ProjectProfileBindingCreate) SetResourceID(v int64) *ProjectProfileBindingCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProjectProfileBindingCreate) SetCreatedAt(v time.Time) *ProjectProfileBindingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProjectProfileBindingCreate) SetNillableCreatedAt(v *time.Time) *ProjectProfileBindingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *ProjectProfileBindingCreate) SetMetadata(v map[string]interface{}) *ProjectProfileBindingCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetProfileID sets the "profile" edge to the ProjectProfile entity by ID.
func (_c *ProjectProfileBindingCreate) SetProfileID(id int64) *ProjectProfileBindingCreate {
	_c.mutation.SetProfileID(id)
	return _c
}

// SetProfile sets the "profile" edge to the ProjectProfile entity.
func (_c *ProjectProfileBindingCreate) SetProfile(v *ProjectProfile) *ProjectProfileBindingCreate {
	return _c.SetProfileID(v.ID)
}

// Mutation returns the ProjectProfileBindingMutation object of the builder.
func (_c *ProjectProfileBindingCreate) Mutation() *ProjectProfileBindingMutation {
	return _c.mutation
}

// Save creates the ProjectProfileBinding in the database.
func (_c *ProjectProfileBindingCreate) Save(ctx context.Context) (*ProjectProfileBinding, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProjectProfileBindingCreate) SaveX(ctx context.Context) *ProjectProfileBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectProfileBindingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectProfileBindingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProjectProfileBindingCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := projectprofilebinding.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		v := projectprofilebinding.DefaultMetadata()
		_c.mutation.SetMetadata(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProjectProfileBindingCreate) check() error {
	if _, ok := _c.mutation.ProjectProfileID(); !ok {
		return &ValidationError{Name: "project_profile_id", err: errors.New(`ent: missing required field "ProjectProfileBinding.project_profile_id"`)}
	}
	if _, ok := _c.mutation.ResourceType(); !ok {
		return &ValidationError{Name: "resource_type", err: errors.New(`ent: missing required field "ProjectProfileBinding.resource_type"`)}
	}
	if v, ok := _c.mutation.ResourceType(); ok {
		if err := projectprofilebinding.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "ProjectProfileBinding.resource_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`ent: missing required field "ProjectProfileBinding.resource_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProjectProfileBinding.created_at"`)}
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "ProjectProfileBinding.metadata"`)}
	}
	if len(_c.mutation.ProfileIDs()) == 0 {
		return &ValidationError{Name: "profile", err: errors.New(`ent: missing required edge "ProjectProfileBinding.profile"`)}
	}
	return nil
}

func (_c *ProjectProfileBindingCreate) sqlSave(ctx context.Context) (*ProjectProfileBinding, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProjectProfileBindingCreate) createSpec() (*ProjectProfileBinding, *sqlgraph.CreateSpec) {
	var (
		_node = &ProjectProfileBinding{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(projectprofilebinding.Table, sqlgraph.NewFieldSpec(projectprofilebinding.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ResourceType(); ok {
		_spec.SetField(projectprofilebinding.FieldResourceType, field.TypeString, value)
		_node.ResourceType = value
	}
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(projectprofilebinding.FieldResourceID, field.TypeInt64, value)
		_node.ResourceID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(projectprofilebinding.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(projectprofilebinding.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if nodes := _c.mutation.ProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectprofilebinding.ProfileTable,
			Columns: []string{projectprofilebinding.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectprofile.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectProfileID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProjectProfileBinding.Create().
//		SetProjectProfileID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProjectProfileBindingUpsert) {
//			SetProjectProfileID(v+v).
//		}).
//		Exec(ctx)
func (_c *ProjectProfileBindingCreate) OnConflict(opts ...sql.ConflictOption) *ProjectProfileBindingUpsertOne {
	_c.conflict = opts
	return &ProjectProfileBindingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProjectProfileBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProjectProfileBindingCreate) OnConflictColumns(columns ...string) *ProjectProfileBindingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProjectProfileBindingUpsertOne{
		create: _c,
	}
}

type (
	// ProjectProfileBindingUpsertOne is the builder for "upsert"-ing
	//  one ProjectProfileBinding node.
	ProjectProfileBindingUpsertOne struct {
		create *ProjectProfileBindingCreate
	}

	// ProjectProfileBindingUpsert is the "OnConflict" setter.
	ProjectProfileBindingUpsert struct {
		*sql.UpdateSet
	}
)

// SetProjectProfileID sets the "project_profile_id" field.
func (u *ProjectProfileBindingUpsert) SetProjectProfileID(v int64) *ProjectProfileBindingUpsert {
	u.Set(projectprofilebinding.FieldProjectProfileID, v)
	return u
}

// UpdateProjectProfileID sets the "project_profile_id" field to the value that was provided on create.
func (u *ProjectProfileBindingUpsert) UpdateProjectProfileID() *ProjectProfileBindingUpsert {
	u.SetExcluded(projectprofilebinding.FieldProjectProfileID)
	return u
}

// SetResourceType sets the "resource_type" field.
func (u *ProjectProfileBindingUpsert) SetResourceType(v string) *ProjectProfileBindingUpsert {
	u.Set(projectprofilebinding.FieldResourceType, v)
	return u
}

// UpdateResourceType sets the "resource_type" field to the value that was provided on create.
func (u *ProjectProfileBindingUpsert) UpdateResourceType() *ProjectProfileBindingUpsert {
	u.SetExcluded(projectprofilebinding.FieldResourceType)
	return u
}

// SetResourceID sets the "resource_id" field.
func (u *ProjectProfileBindingUpsert) SetResourceID(v int64) *ProjectProfileBindingUpsert {
	u.Set(projectprofilebinding.FieldResourceID, v)
	return u
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *ProjectProfileBindingUpsert) UpdateResourceID() *ProjectProfileBindingUpsert {
	u.SetExcluded(projectprofilebinding.FieldResourceID)
	return u
}

// AddResourceID adds v to the "resource_id" field.
func (u *ProjectProfileBindingUpsert) AddResourceID(v int64) *ProjectProfileBindingUpsert {
	u.Add(projectprofilebinding.FieldResourceID, v)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *ProjectProfileBindingUpsert) SetMetadata(v map[string]interface{}) *ProjectProfileBindingUpsert {
	u.Set(projectprofilebinding.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *ProjectProfileBindingUpsert) UpdateMetadata() *ProjectProfileBindingUpsert {
	u.SetExcluded(projectprofilebinding.FieldMetadata)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ProjectProfileBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProjectProfileBindingUpsertOne) UpdateNewValues() *ProjectProfileBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(projectprofilebinding.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProjectProfileBinding.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProjectProfileBindingUpsertOne) Ignore() *ProjectProfileBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProjectProfileBindingUpsertOne) DoNothing() *ProjectProfileBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProjectProfileBindingCreate.OnConflict
// documentation for more info.
func (u *ProjectProfileBindingUpsertOne) Update(set func(*ProjectProfileBindingUpsert)) *ProjectProfileBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProjectProfileBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetProjectProfileID sets the "project_profile_id" field.
func (u *ProjectProfileBindingUpsertOne) SetProjectProfileID(v int64) *ProjectProfileBindingUpsertOne {
	return u.Update(func(s *ProjectProfileBindingUpsert) {
		s.SetProjectProfileID(v)
	})
}

// UpdateProjectProfileID sets the "project_profile_id" field to the value that was provided on create.
func (u *ProjectProfileBindingUpsertOne) UpdateProjectProfileID() *ProjectProfileBindingUpsertOne {
	return u.Update(func(s *ProjectProfileBindingUpsert) {
		s.UpdateProjectProfileID()
	})
}

// SetResourceType sets the "resource_type" field.
func (u *ProjectProfileBindingUpsertOne) SetResourceType(v string) *ProjectProfileBindingUpsertOne {
	return u.Update(func(s *ProjectProfileBindingUpsert) {
		s.SetResourceType(v)
	})
}

// UpdateResourceType sets the "resource_type" field to the value that was provided on create.
func (u *ProjectProfileBindingUpsertOne) UpdateResourceType() *ProjectProfileBindingUpsertOne {
	return u.Update(func(s *ProjectProfileBindingUpsert) {
		s.UpdateResourceType()
	})
}

// SetResourceID sets the "resource_id" field.
func (u *ProjectProfileBindingUpsertOne) SetResourceID(v int64) *ProjectProfileBindingUpsertOne {
	return u.Update(func(s *ProjectProfileBindingUpsert) {
		s.SetResourceID(v)
	})
}

// AddResourceID adds v to the "resource_id" field.
func (u *ProjectProfileBindingUpsertOne) AddResourceID(v int64) *ProjectProfileBindingUpsertOne {
	return u.Update(func(s *ProjectProfileBindingUpsert) {
		s.AddResourceID(v)
	})
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *ProjectProfileBindingUpsertOne) UpdateResourceID() *ProjectProfileBindingUpsertOne {
	return u.Update(func(s *ProjectProfileBindingUpsert) {
		s.UpdateResourceID()
	})
}

// SetMetadata sets the "metadata" field.
func (u *ProjectProfileBindingUpsertOne) SetMetadata(v map[string]interface{}) *ProjectProfileBindingUpsertOne {
	return u.Update(func(s *ProjectProfileBindingUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *ProjectProfileBindingUpsertOne) UpdateMetadata() *ProjectProfileBindingUpsertOne {
	return u.Update(func(s *ProjectProfileBindingUpsert) {
		s.UpdateMetadata()
	})
}

// Exec executes the query.
func (u *ProjectProfileBindingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProjectProfileBindingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProjectProfileBindingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProjectProfileBindingUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProjectProfileBindingUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProjectProfileBindingCreateBulk is the builder for creating many ProjectProfileBinding entities in bulk.
type ProjectProfileBindingCreateBulk struct {
	config
	err      error
	builders []*ProjectProfileBindingCreate
	conflict []sql.ConflictOption
}

// Save creates the ProjectProfileBinding entities in the database.
func (_c *ProjectProfileBindingCreateBulk) Save(ctx context.Context) ([]*ProjectProfileBinding, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProjectProfileBinding, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProjectProfileBindingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProjectProfileBindingCreateBulk) SaveX(ctx context.Context) []*ProjectProfileBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectProfileBindingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectProfileBindingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProjectProfileBinding.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProjectProfileBindingUpsert) {
//			SetProjectProfileID(v+v).
//		}).
//		Exec(ctx)
func (_c *ProjectProfileBindingCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProjectProfileBindingUpsertBulk {
	_c.conflict = opts
	return &ProjectProfileBindingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProjectProfileBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProjectProfileBindingCreateBulk) OnConflictColumns(columns ...string) *ProjectProfileBindingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProjectProfileBindingUpsertBulk{
		create: _c,
	}
}

// ProjectProfileBindingUpsertBulk is the builder for "upsert"-ing
// a bulk of ProjectProfileBinding nodes.
type ProjectProfileBindingUpsertBulk struct {
	create *ProjectProfileBindingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ProjectProfileBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProjectProfileBindingUpsertBulk) UpdateNewValues() *ProjectProfileBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(projectprofilebinding.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProjectProfileBinding.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProjectProfileBindingUpsertBulk) Ignore() *ProjectProfileBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProjectProfileBindingUpsertBulk) DoNothing() *ProjectProfileBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProjectProfileBindingCreateBulk.OnConflict
// documentation for more info.
func (u *ProjectProfileBindingUpsertBulk) Update(set func(*ProjectProfileBindingUpsert)) *ProjectProfileBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProjectProfileBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetProjectProfileID sets the "project_profile_id" field.
func (u *ProjectProfileBindingUpsertBulk) SetProjectProfileID(v int64) *ProjectProfileBindingUpsertBulk {
	return u.Update(func(s *ProjectProfileBindingUpsert) {
		s.SetProjectProfileID(v)
	})
}

// UpdateProjectProfileID sets the "project_profile_id" field to the value that was provided on create.
func (u *ProjectProfileBindingUpsertBulk) UpdateProjectProfileID() *ProjectProfileBindingUpsertBulk {
	return u.Update(func(s *ProjectProfileBindingUpsert) {
		s.UpdateProjectProfileID()
	})
}

// SetResourceType sets the "resource_type" field.
func (u *ProjectProfileBindingUpsertBulk) SetResourceType(v string) *ProjectProfileBindingUpsertBulk {
	return u.Update(func(s *ProjectProfileBindingUpsert) {
		s.SetResourceType(v)
	})
}

// UpdateResourceType sets the "resource_type" field to the value that was provided on create.
func (u *ProjectProfileBindingUpsertBulk) UpdateResourceType() *ProjectProfileBindingUpsertBulk {
	return u.Update(func(s *ProjectProfileBindingUpsert) {
		s.UpdateResourceType()
	})
}

// SetResourceID sets the "resource_id" field.
func (u *ProjectProfileBindingUpsertBulk) SetResourceID(v int64) *ProjectProfileBindingUpsertBulk {
	return u.Update(func(s *ProjectProfileBindingUpsert) {
		s.SetResourceID(v)
	})
}

// AddResourceID adds v to the "resource_id" field.
func (u *ProjectProfileBindingUpsertBulk) AddResourceID(v int64) *ProjectProfileBindingUpsertBulk {
	return u.Update(func(s *ProjectProfileBindingUpsert) {
		s.AddResourceID(v)
	})
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *ProjectProfileBindingUpsertBulk) UpdateResourceID() *ProjectProfileBindingUpsertBulk {
	return u.Update(func(s *ProjectProfileBindingUpsert) {
		s.UpdateResourceID()
	})
}

// SetMetadata sets the "metadata" field.
func (u *ProjectProfileBindingUpsertBulk) SetMetadata(v map[string]interface{}) *ProjectProfileBindingUpsertBulk {
	return u.Update(func(s *ProjectProfileBindingUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *ProjectProfileBindingUpsertBulk) UpdateMetadata() *ProjectProfileBindingUpsertBulk {
	return u.Update(func(s *ProjectProfileBindingUpsert) {
		s.UpdateMetadata()
	})
}

// Exec executes the query.
func (u *ProjectProfileBindingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProjectProfileBindingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProjectProfileBindingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProjectProfileBindingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
