// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/projectprofile"
	"github.com/Wei-Shaw/sub2api/ent/projectprofilebinding"
)

// ProjectProfileBindingUpdate is the builder for updating ProjectProfileBinding entities.
type ProjectProfileBindingUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectProfileBindingMutation
}

// Where appends a list predicates to the ProjectProfileBindingUpdate builder.
func (_u *ProjectProfileBindingUpdate) Where(ps ...predicate.ProjectProfileBinding) *ProjectProfileBindingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProjectProfileID sets the "project_profile_id" field.
func (_u *ProjectProfileBindingUpdate) SetProjectProfileID(v int64) *ProjectProfileBindingUpdate {
	_u.mutation.SetProjectProfileID(v)
	return _u
}

// SetNillableProjectProfileID sets the "project_profile_id" field if the given value is not nil.
func (_u *ProjectProfileBindingUpdate) SetNillableProjectProfileID(v *int64) *ProjectProfileBindingUpdate {
	if v != nil {
		_u.SetProjectProfileID(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *ProjectProfileBindingUpdate) SetResourceType(v string) *ProjectProfileBindingUpdate {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *ProjectProfileBindingUpdate) SetNillableResourceType(v *string) *ProjectProfileBindingUpdate {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *ProjectProfileBindingUpdate) SetResourceID(v int64) *ProjectProfileBindingUpdate {
	_u.mutation.ResetResourceID()
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *ProjectProfileBindingUpdate) SetNillableResourceID(v *int64) *ProjectProfileBindingUpdate {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// AddResourceID adds value to the "resource_id" field.
func (_u *ProjectProfileBindingUpdate) AddResourceID(v int64) *ProjectProfileBindingUpdate {
	_u.mutation.AddResourceID(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *ProjectProfileBindingUpdate) SetMetadata(v map[string]interface{}) *ProjectProfileBindingUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetProfileID sets the "profile" edge to the ProjectProfile entity by ID.
func (_u *ProjectProfileBindingUpdate) SetProfileID(id int64) *ProjectProfileBindingUpdate {
	_u.mutation.SetProfileID(id)
	return _u
}

// SetProfile sets the "profile" edge to the ProjectProfile entity.
func (_u *ProjectProfileBindingUpdate) SetProfile(v *ProjectProfile) *ProjectProfileBindingUpdate {
	return _u.SetProfileID(v.ID)
}

// Mutation returns the ProjectProfileBindingMutation object of the builder.
func (_u *ProjectProfileBindingUpdate) Mutation() *ProjectProfileBindingMutation {
	return _u.mutation
}

// ClearProfile clears the "profile" edge to the ProjectProfile entity.
func (_u *ProjectProfileBindingUpdate) ClearProfile() *ProjectProfileBindingUpdate {
	_u.mutation.ClearProfile()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProjectProfileBindingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectProfileBindingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProjectProfileBindingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectProfileBindingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectProfileBindingUpdate) check() error {
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := projectprofilebinding.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "ProjectProfileBinding.resource_type": %w`, err)}
		}
	}
	if _u.mutation.ProfileCleared() && len(_u.mutation.ProfileIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectProfileBinding.profile"`)
	}
	return nil
}

func (_u *ProjectProfileBindingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(projectprofilebinding.Table, projectprofilebinding.Columns, sqlgraph.NewFieldSpec(projectprofilebinding.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(projectprofilebinding.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(projectprofilebinding.FieldResourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedResourceID(); ok {
		_spec.AddField(projectprofilebinding.FieldResourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(projectprofilebinding.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.ProfileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectprofilebinding.ProfileTable,
			Columns: []string{projectprofilebinding.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectprofile.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectprofilebinding.ProfileTable,
			Columns: []string{projectprofilebinding.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectprofile.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projectprofilebinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProjectProfileBindingUpdateOne is the builder for updating a single ProjectProfileBinding entity.
type ProjectProfileBindingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectProfileBindingMutation
}

// SetProjectProfileID sets the "project_profile_id" field.
func (_u *ProjectProfileBindingUpdateOne) SetProjectProfileID(v int64) *ProjectProfileBindingUpdateOne {
	_u.mutation.SetProjectProfileID(v)
	return _u
}

// SetNillableProjectProfileID sets the "project_profile_id" field if the given value is not nil.
func (_u *ProjectProfileBindingUpdateOne) SetNillableProjectProfileID(v *int64) *ProjectProfileBindingUpdateOne {
	if v != nil {
		_u.SetProjectProfileID(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *ProjectProfileBindingUpdateOne) SetResourceType(v string) *ProjectProfileBindingUpdateOne {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *ProjectProfileBindingUpdateOne) SetNillableResourceType(v *string) *ProjectProfileBindingUpdateOne {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *ProjectProfileBindingUpdateOne) SetResourceID(v int64) *ProjectProfileBindingUpdateOne {
	_u.mutation.ResetResourceID()
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *ProjectProfileBindingUpdateOne) SetNillableResourceID(v *int64) *ProjectProfileBindingUpdateOne {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// AddResourceID adds value to the "resource_id" field.
func (_u *ProjectProfileBindingUpdateOne) AddResourceID(v int64) *ProjectProfileBindingUpdateOne {
	_u.mutation.AddResourceID(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *ProjectProfileBindingUpdateOne) SetMetadata(v map[string]interface{}) *ProjectProfileBindingUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetProfileID sets the "profile" edge to the ProjectProfile entity by ID.
func (_u *ProjectProfileBindingUpdateOne) SetProfileID(id int64) *ProjectProfileBindingUpdateOne {
	_u.mutation.SetProfileID(id)
	return _u
}

// SetProfile sets the "profile" edge to the ProjectProfile entity.
func (_u *ProjectProfileBindingUpdateOne) SetProfile(v *ProjectProfile) *ProjectProfileBindingUpdateOne {
	return _u.SetProfileID(v.ID)
}

// Mutation returns the ProjectProfileBindingMutation object of the builder.
func (_u *ProjectProfileBindingUpdateOne) Mutation() *ProjectProfileBindingMutation {
	return _u.mutation
}

// ClearProfile clears the "profile" edge to the ProjectProfile entity.
func (_u *ProjectProfileBindingUpdateOne) ClearProfile() *ProjectProfileBindingUpdateOne {
	_u.mutation.ClearProfile()
	return _u
}

// Where appends a list predicates to the ProjectProfileBindingUpdate builder.
func (_u *ProjectProfileBindingUpdateOne) Where(ps ...predicate.ProjectProfileBinding) *ProjectProfileBindingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProjectProfileBindingUpdateOne) Select(field string, fields ...string) *ProjectProfileBindingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProjectProfileBinding entity.
func (_u *ProjectProfileBindingUpdateOne) Save(ctx context.Context) (*ProjectProfileBinding, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectProfileBindingUpdateOne) SaveX(ctx context.Context) *ProjectProfileBinding {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProjectProfileBindingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectProfileBindingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectProfileBindingUpdateOne) check() error {
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := projectprofilebinding.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "ProjectProfileBinding.resource_type": %w`, err)}
		}
	}
	if _u.mutation.ProfileCleared() && len(_u.mutation.ProfileIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectProfileBinding.profile"`)
	}
	return nil
}

func (_u *ProjectProfileBindingUpdateOne) sqlSave(ctx context.Context) (_node *ProjectProfileBinding, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(projectprofilebinding.Table, projectprofilebinding.Columns, sqlgraph.NewFieldSpec(projectprofilebinding.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProjectProfileBinding.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, projectprofilebinding.FieldID)
		for _, f := range fields {
			if !projectprofilebinding.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != projectprofilebinding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(projectprofilebinding.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(projectprofilebinding.FieldResourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedResourceID(); ok {
		_spec.AddField(projectprofilebinding.FieldResourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(projectprofilebinding.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.ProfileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectprofilebinding.ProfileTable,
			Columns: []string{projectprofilebinding.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectprofile.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectprofilebinding.ProfileTable,
			Columns: []string{projectprofilebinding.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectprofile.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProjectProfileBinding{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projectprofilebinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
