// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/projectprofile"
	"github.com/Wei-Shaw/sub2api/ent/projectprofilebinding"
)

// ProjectProfileBinding is the model entity for the ProjectProfileBinding schema.
type ProjectProfileBinding struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ProjectProfileID holds the value of the "project_profile_id" field.
	ProjectProfileID int64 `json:"project_profile_id,omitempty"`
	// ResourceType holds the value of the "resource_type" field.
	ResourceType string `json:"resource_type,omitempty"`
	// ResourceID holds the value of the "resource_id" field.
	ResourceID int64 `json:"resource_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProjectProfileBindingQuery when eager-loading is set.
	Edges        ProjectProfileBindingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProjectProfileBindingEdges holds the relations/edges for other nodes in the graph.
type ProjectProfileBindingEdges struct {
	// Profile holds the value of the profile edge.
	Profile *ProjectProfile `json:"profile,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ProfileOrErr returns the Profile value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProjectProfileBindingEdges) ProfileOrErr() (*ProjectProfile, error) {
	if e.Profile != nil {
		return e.Profile, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: projectprofile.Label}
	}
	return nil, &NotLoadedError{edge: "profile"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProjectProfileBinding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case projectprofilebinding.FieldMetadata:
			values[i] = new([]byte)
		case projectprofilebinding.FieldID, projectprofilebinding.FieldProjectProfileID, projectprofilebinding.FieldResourceID:
			values[i] = new(sql.NullInt64)
		case projectprofilebinding.FieldResourceType:
			values[i] = new(sql.NullString)
		case projectprofilebinding.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProjectProfileBinding fields.
func (_m *ProjectProfileBinding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case projectprofilebinding.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case projectprofilebinding.FieldProjectProfileID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field project_profile_id", values[i])
			} else if value.Valid {
				_m.ProjectProfileID = value.Int64
			}
		case projectprofilebinding.FieldResourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resource_type", values[i])
			} else if value.Valid {
				_m.ResourceType = value.String
			}
		case projectprofilebinding.FieldResourceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field resource_id", values[i])
			} else if value.Valid {
				_m.ResourceID = value.Int64
			}
		case projectprofilebinding.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case projectprofilebinding.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProjectProfileBinding.
// This includes values selected through modifiers, order, etc.
func (_m *ProjectProfileBinding) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProfile queries the "profile" edge of the ProjectProfileBinding entity.
func (_m *ProjectProfileBinding) QueryProfile() *ProjectProfileQuery {
	return NewProjectProfileBindingClient(_m.config).QueryProfile(_m)
}

// Update returns a builder for updating this ProjectProfileBinding.
// Note that you need to call ProjectProfileBinding.Unwrap() before calling this method if this ProjectProfileBinding
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProjectProfileBinding) Update() *ProjectProfileBindingUpdateOne {
	return NewProjectProfileBindingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProjectProfileBinding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProjectProfileBinding) Unwrap() *ProjectProfileBinding {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProjectProfileBinding is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProjectProfileBinding) String() string {
	var builder strings.Builder
	builder.WriteString("ProjectProfileBinding(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("project_profile_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectProfileID))
	builder.WriteString(", ")
	builder.WriteString("resource_type=")
	builder.WriteString(_m.ResourceType)
	builder.WriteString(", ")
	builder.WriteString("resource_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResourceID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteByte(')')
	return builder.String()
}

// ProjectProfileBindings is a parsable slice of ProjectProfileBinding.
type ProjectProfileBindings []*ProjectProfileBinding
