// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usergroupratelimitwindow"
)

// UserGroupRateLimitWindowCreate is the builder for creating a UserGroupRateLimitWindow entity.
type UserGroupRateLimitWindowCreate struct {
	config
	mutation *UserGroupRateLimitWindowMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserGroupRateLimitWindowCreate) SetCreatedAt(v time.Time) *UserGroupRateLimitWindowCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserGroupRateLimitWindowCreate) SetNillableCreatedAt(v *time.Time) *UserGroupRateLimitWindowCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserGroupRateLimitWindowCreate) SetUpdatedAt(v time.Time) *UserGroupRateLimitWindowCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserGroupRateLimitWindowCreate) SetNillableUpdatedAt(v *time.Time) *UserGroupRateLimitWindowCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *UserGroupRateLimitWindowCreate) SetDeletedAt(v time.Time) *UserGroupRateLimitWindowCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *UserGroupRateLimitWindowCreate) SetNillableDeletedAt(v *time.Time) *UserGroupRateLimitWindowCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserGroupRateLimitWindowCreate) SetUserID(v int64) *UserGroupRateLimitWindowCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *UserGroupRateLimitWindowCreate) SetGroupID(v int64) *UserGroupRateLimitWindowCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetUsage5hUsd sets the "usage_5h_usd" field.
func (_c *UserGroupRateLimitWindowCreate) SetUsage5hUsd(v float64) *UserGroupRateLimitWindowCreate {
	_c.mutation.SetUsage5hUsd(v)
	return _c
}

// SetNillableUsage5hUsd sets the "usage_5h_usd" field if the given value is not nil.
func (_c *UserGroupRateLimitWindowCreate) SetNillableUsage5hUsd(v *float64) *UserGroupRateLimitWindowCreate {
	if v != nil {
		_c.SetUsage5hUsd(*v)
	}
	return _c
}

// SetWindow5hStart sets the "window_5h_start" field.
func (_c *UserGroupRateLimitWindowCreate) SetWindow5hStart(v time.Time) *UserGroupRateLimitWindowCreate {
	_c.mutation.SetWindow5hStart(v)
	return _c
}

// SetNillableWindow5hStart sets the "window_5h_start" field if the given value is not nil.
func (_c *UserGroupRateLimitWindowCreate) SetNillableWindow5hStart(v *time.Time) *UserGroupRateLimitWindowCreate {
	if v != nil {
		_c.SetWindow5hStart(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserGroupRateLimitWindowCreate) SetUser(v *User) *UserGroupRateLimitWindowCreate {
	return _c.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *UserGroupRateLimitWindowCreate) SetGroup(v *Group) *UserGroupRateLimitWindowCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the UserGroupRateLimitWindowMutation object of the builder.
func (_c *UserGroupRateLimitWindowCreate) Mutation() *UserGroupRateLimitWindowMutation {
	return _c.mutation
}

// Save creates the UserGroupRateLimitWindow in the database.
func (_c *UserGroupRateLimitWindowCreate) Save(ctx context.Context) (*UserGroupRateLimitWindow, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserGroupRateLimitWindowCreate) SaveX(ctx context.Context) *UserGroupRateLimitWindow {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserGroupRateLimitWindowCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserGroupRateLimitWindowCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserGroupRateLimitWindowCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if usergroupratelimitwindow.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized usergroupratelimitwindow.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := usergroupratelimitwindow.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if usergroupratelimitwindow.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized usergroupratelimitwindow.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := usergroupratelimitwindow.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Usage5hUsd(); !ok {
		v := usergroupratelimitwindow.DefaultUsage5hUsd
		_c.mutation.SetUsage5hUsd(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserGroupRateLimitWindowCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserGroupRateLimitWindow.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserGroupRateLimitWindow.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserGroupRateLimitWindow.user_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "UserGroupRateLimitWindow.group_id"`)}
	}
	if _, ok := _c.mutation.Usage5hUsd(); !ok {
		return &ValidationError{Name: "usage_5h_usd", err: errors.New(`ent: missing required field "UserGroupRateLimitWindow.usage_5h_usd"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserGroupRateLimitWindow.user"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "UserGroupRateLimitWindow.group"`)}
	}
	return nil
}

func (_c *UserGroupRateLimitWindowCreate) sqlSave(ctx context.Context) (*UserGroupRateLimitWindow, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserGroupRateLimitWindowCreate) createSpec() (*UserGroupRateLimitWindow, *sqlgraph.CreateSpec) {
	var (
		_node = &UserGroupRateLimitWindow{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usergroupratelimitwindow.Table, sqlgraph.NewFieldSpec(usergroupratelimitwindow.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usergroupratelimitwindow.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(usergroupratelimitwindow.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(usergroupratelimitwindow.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Usage5hUsd(); ok {
		_spec.SetField(usergroupratelimitwindow.FieldUsage5hUsd, field.TypeFloat64, value)
		_node.Usage5hUsd = value
	}
	if value, ok := _c.mutation.Window5hStart(); ok {
		_spec.SetField(usergroupratelimitwindow.FieldWindow5hStart, field.TypeTime, value)
		_node.Window5hStart = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usergroupratelimitwindow.UserTable,
			Columns: []string{usergroupratelimitwindow.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usergroupratelimitwindow.GroupTable,
			Columns: []string{usergroupratelimitwindow.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserGroupRateLimitWindow.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserGroupRateLimitWindowUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserGroupRateLimitWindowCreate) OnConflict(opts ...sql.ConflictOption) *UserGroupRateLimitWindowUpsertOne {
	_c.conflict = opts
	return &UserGroupRateLimitWindowUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserGroupRateLimitWindow.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserGroupRateLimitWindowCreate) OnConflictColumns(columns ...string) *UserGroupRateLimitWindowUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserGroupRateLimitWindowUpsertOne{
		create: _c,
	}
}

type (
	// UserGroupRateLimitWindowUpsertOne is the builder for "upsert"-ing
	//  one UserGroupRateLimitWindow node.
	UserGroupRateLimitWindowUpsertOne struct {
		create *UserGroupRateLimitWindowCreate
	}

	// UserGroupRateLimitWindowUpsert is the "OnConflict" setter.
	UserGroupRateLimitWindowUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UserGroupRateLimitWindowUpsert) SetUpdatedAt(v time.Time) *UserGroupRateLimitWindowUpsert {
	u.Set(usergroupratelimitwindow.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserGroupRateLimitWindowUpsert) UpdateUpdatedAt() *UserGroupRateLimitWindowUpsert {
	u.SetExcluded(usergroupratelimitwindow.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UserGroupRateLimitWindowUpsert) SetDeletedAt(v time.Time) *UserGroupRateLimitWindowUpsert {
	u.Set(usergroupratelimitwindow.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UserGroupRateLimitWindowUpsert) UpdateDeletedAt() *UserGroupRateLimitWindowUpsert {
	u.SetExcluded(usergroupratelimitwindow.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UserGroupRateLimitWindowUpsert) ClearDeletedAt() *UserGroupRateLimitWindowUpsert {
	u.SetNull(usergroupratelimitwindow.FieldDeletedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserGroupRateLimitWindowUpsert) SetUserID(v int64) *UserGroupRateLimitWindowUpsert {
	u.Set(usergroupratelimitwindow.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserGroupRateLimitWindowUpsert) UpdateUserID() *UserGroupRateLimitWindowUpsert {
	u.SetExcluded(usergroupratelimitwindow.FieldUserID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *UserGroupRateLimitWindowUpsert) SetGroupID(v int64) *UserGroupRateLimitWindowUpsert {
	u.Set(usergroupratelimitwindow.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UserGroupRateLimitWindowUpsert) UpdateGroupID() *UserGroupRateLimitWindowUpsert {
	u.SetExcluded(usergroupratelimitwindow.FieldGroupID)
	return u
}

// SetUsage5hUsd sets the "usage_5h_usd" field.
func (u *UserGroupRateLimitWindowUpsert) SetUsage5hUsd(v float64) *UserGroupRateLimitWindowUpsert {
	u.Set(usergroupratelimitwindow.FieldUsage5hUsd, v)
	return u
}

// UpdateUsage5hUsd sets the "usage_5h_usd" field to the value that was provided on create.
func (u *UserGroupRateLimitWindowUpsert) UpdateUsage5hUsd() *UserGroupRateLimitWindowUpsert {
	u.SetExcluded(usergroupratelimitwindow.FieldUsage5hUsd)
	return u
}

// AddUsage5hUsd adds v to the "usage_5h_usd" field.
func (u *UserGroupRateLimitWindowUpsert) AddUsage5hUsd(v float64) *UserGroupRateLimitWindowUpsert {
	u.Add(usergroupratelimitwindow.FieldUsage5hUsd, v)
	return u
}

// SetWindow5hStart sets the "window_5h_start" field.
func (u *UserGroupRateLimitWindowUpsert) SetWindow5hStart(v time.Time) *UserGroupRateLimitWindowUpsert {
	u.Set(usergroupratelimitwindow.FieldWindow5hStart, v)
	return u
}

// UpdateWindow5hStart sets the "window_5h_start" field to the value that was provided on create.
func (u *UserGroupRateLimitWindowUpsert) UpdateWindow5hStart() *UserGroupRateLimitWindowUpsert {
	u.SetExcluded(usergroupratelimitwindow.FieldWindow5hStart)
	return u
}

// ClearWindow5hStart clears the value of the "window_5h_start" field.
func (u *UserGroupRateLimitWindowUpsert) ClearWindow5hStart() *UserGroupRateLimitWindowUpsert {
	u.SetNull(usergroupratelimitwindow.FieldWindow5hStart)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserGroupRateLimitWindow.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserGroupRateLimitWindowUpsertOne) UpdateNewValues() *UserGroupRateLimitWindowUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usergroupratelimitwindow.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserGroupRateLimitWindow.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserGroupRateLimitWindowUpsertOne) Ignore() *UserGroupRateLimitWindowUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserGroupRateLimitWindowUpsertOne) DoNothing() *UserGroupRateLimitWindowUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserGroupRateLimitWindowCreate.OnConflict
// documentation for more info.
func (u *UserGroupRateLimitWindowUpsertOne) Update(set func(*UserGroupRateLimitWindowUpsert)) *UserGroupRateLimitWindowUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserGroupRateLimitWindowUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserGroupRateLimitWindowUpsertOne) SetUpdatedAt(v time.Time) *UserGroupRateLimitWindowUpsertOne {
	return u.Update(func(s *UserGroupRateLimitWindowUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserGroupRateLimitWindowUpsertOne) UpdateUpdatedAt() *UserGroupRateLimitWindowUpsertOne {
	return u.Update(func(s *UserGroupRateLimitWindowUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UserGroupRateLimitWindowUpsertOne) SetDeletedAt(v time.Time) *UserGroupRateLimitWindowUpsertOne {
	return u.Update(func(s *UserGroupRateLimitWindowUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UserGroupRateLimitWindowUpsertOne) UpdateDeletedAt() *UserGroupRateLimitWindowUpsertOne {
	return u.Update(func(s *UserGroupRateLimitWindowUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UserGroupRateLimitWindowUpsertOne) ClearDeletedAt() *UserGroupRateLimitWindowUpsertOne {
	return u.Update(func(s *UserGroupRateLimitWindowUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserGroupRateLimitWindowUpsertOne) SetUserID(v int64) *UserGroupRateLimitWindowUpsertOne {
	return u.Update(func(s *UserGroupRateLimitWindowUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserGroupRateLimitWindowUpsertOne) UpdateUserID() *UserGroupRateLimitWindowUpsertOne {
	return u.Update(func(s *UserGroupRateLimitWindowUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *UserGroupRateLimitWindowUpsertOne) SetGroupID(v int64) *UserGroupRateLimitWindowUpsertOne {
	return u.Update(func(s *UserGroupRateLimitWindowUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UserGroupRateLimitWindowUpsertOne) UpdateGroupID() *UserGroupRateLimitWindowUpsertOne {
	return u.Update(func(s *UserGroupRateLimitWindowUpsert) {
		s.UpdateGroupID()
	})
}

// SetUsage5hUsd sets the "usage_5h_usd" field.
func (u *UserGroupRateLimitWindowUpsertOne) SetUsage5hUsd(v float64) *UserGroupRateLimitWindowUpsertOne {
	return u.Update(func(s *UserGroupRateLimitWindowUpsert) {
		s.SetUsage5hUsd(v)
	})
}

// AddUsage5hUsd adds v to the "usage_5h_usd" field.
func (u *UserGroupRateLimitWindowUpsertOne) AddUsage5hUsd(v float64) *UserGroupRateLimitWindowUpsertOne {
	return u.Update(func(s *UserGroupRateLimitWindowUpsert) {
		s.AddUsage5hUsd(v)
	})
}

// UpdateUsage5hUsd sets the "usage_5h_usd" field to the value that was provided on create.
func (u *UserGroupRateLimitWindowUpsertOne) UpdateUsage5hUsd() *UserGroupRateLimitWindowUpsertOne {
	return u.Update(func(s *UserGroupRateLimitWindowUpsert) {
		s.UpdateUsage5hUsd()
	})
}

// SetWindow5hStart sets the "window_5h_start" field.
func (u *UserGroupRateLimitWindowUpsertOne) SetWindow5hStart(v time.Time) *UserGroupRateLimitWindowUpsertOne {
	return u.Update(func(s *UserGroupRateLimitWindowUpsert) {
		s.SetWindow5hStart(v)
	})
}

// UpdateWindow5hStart sets the "window_5h_start" field to the value that was provided on create.
func (u *UserGroupRateLimitWindowUpsertOne) UpdateWindow5hStart() *UserGroupRateLimitWindowUpsertOne {
	return u.Update(func(s *UserGroupRateLimitWindowUpsert) {
		s.UpdateWindow5hStart()
	})
}

// ClearWindow5hStart clears the value of the "window_5h_start" field.
func (u *UserGroupRateLimitWindowUpsertOne) ClearWindow5hStart() *UserGroupRateLimitWindowUpsertOne {
	return u.Update(func(s *UserGroupRateLimitWindowUpsert) {
		s.ClearWindow5hStart()
	})
}

// Exec executes the query.
func (u *UserGroupRateLimitWindowUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserGroupRateLimitWindowCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserGroupRateLimitWindowUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserGroupRateLimitWindowUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserGroupRateLimitWindowUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserGroupRateLimitWindowCreateBulk is the builder for creating many UserGroupRateLimitWindow entities in bulk.
type UserGroupRateLimitWindowCreateBulk struct {
	config
	err      error
	builders []*UserGroupRateLimitWindowCreate
	conflict []sql.ConflictOption
}

// Save creates the UserGroupRateLimitWindow entities in the database.
func (_c *UserGroupRateLimitWindowCreateBulk) Save(ctx context.Context) ([]*UserGroupRateLimitWindow, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserGroupRateLimitWindow, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserGroupRateLimitWindowMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserGroupRateLimitWindowCreateBulk) SaveX(ctx context.Context) []*UserGroupRateLimitWindow {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserGroupRateLimitWindowCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserGroupRateLimitWindowCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserGroupRateLimitWindow.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserGroupRateLimitWindowUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserGroupRateLimitWindowCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserGroupRateLimitWindowUpsertBulk {
	_c.conflict = opts
	return &UserGroupRateLimitWindowUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserGroupRateLimitWindow.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserGroupRateLimitWindowCreateBulk) OnConflictColumns(columns ...string) *UserGroupRateLimitWindowUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserGroupRateLimitWindowUpsertBulk{
		create: _c,
	}
}

// UserGroupRateLimitWindowUpsertBulk is the builder for "upsert"-ing
// a bulk of UserGroupRateLimitWindow nodes.
type UserGroupRateLimitWindowUpsertBulk struct {
	create *UserGroupRateLimitWindowCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserGroupRateLimitWindow.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserGroupRateLimitWindowUpsertBulk) UpdateNewValues() *UserGroupRateLimitWindowUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usergroupratelimitwindow.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserGroupRateLimitWindow.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserGroupRateLimitWindowUpsertBulk) Ignore() *UserGroupRateLimitWindowUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserGroupRateLimitWindowUpsertBulk) DoNothing() *UserGroupRateLimitWindowUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserGroupRateLimitWindowCreateBulk.OnConflict
// documentation for more info.
func (u *UserGroupRateLimitWindowUpsertBulk) Update(set func(*UserGroupRateLimitWindowUpsert)) *UserGroupRateLimitWindowUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserGroupRateLimitWindowUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserGroupRateLimitWindowUpsertBulk) SetUpdatedAt(v time.Time) *UserGroupRateLimitWindowUpsertBulk {
	return u.Update(func(s *UserGroupRateLimitWindowUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserGroupRateLimitWindowUpsertBulk) UpdateUpdatedAt() *UserGroupRateLimitWindowUpsertBulk {
	return u.Update(func(s *UserGroupRateLimitWindowUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UserGroupRateLimitWindowUpsertBulk) SetDeletedAt(v time.Time) *UserGroupRateLimitWindowUpsertBulk {
	return u.Update(func(s *UserGroupRateLimitWindowUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UserGroupRateLimitWindowUpsertBulk) UpdateDeletedAt() *UserGroupRateLimitWindowUpsertBulk {
	return u.Update(func(s *UserGroupRateLimitWindowUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UserGroupRateLimitWindowUpsertBulk) ClearDeletedAt() *UserGroupRateLimitWindowUpsertBulk {
	return u.Update(func(s *UserGroupRateLimitWindowUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserGroupRateLimitWindowUpsertBulk) SetUserID(v int64) *UserGroupRateLimitWindowUpsertBulk {
	return u.Update(func(s *UserGroupRateLimitWindowUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserGroupRateLimitWindowUpsertBulk) UpdateUserID() *UserGroupRateLimitWindowUpsertBulk {
	return u.Update(func(s *UserGroupRateLimitWindowUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *UserGroupRateLimitWindowUpsertBulk) SetGroupID(v int64) *UserGroupRateLimitWindowUpsertBulk {
	return u.Update(func(s *UserGroupRateLimitWindowUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UserGroupRateLimitWindowUpsertBulk) UpdateGroupID() *UserGroupRateLimitWindowUpsertBulk {
	return u.Update(func(s *UserGroupRateLimitWindowUpsert) {
		s.UpdateGroupID()
	})
}

// SetUsage5hUsd sets the "usage_5h_usd" field.
func (u *UserGroupRateLimitWindowUpsertBulk) SetUsage5hUsd(v float64) *UserGroupRateLimitWindowUpsertBulk {
	return u.Update(func(s *UserGroupRateLimitWindowUpsert) {
		s.SetUsage5hUsd(v)
	})
}

// AddUsage5hUsd adds v to the "usage_5h_usd" field.
func (u *UserGroupRateLimitWindowUpsertBulk) AddUsage5hUsd(v float64) *UserGroupRateLimitWindowUpsertBulk {
	return u.Update(func(s *UserGroupRateLimitWindowUpsert) {
		s.AddUsage5hUsd(v)
	})
}

// UpdateUsage5hUsd sets the "usage_5h_usd" field to the value that was provided on create.
func (u *UserGroupRateLimitWindowUpsertBulk) UpdateUsage5hUsd() *UserGroupRateLimitWindowUpsertBulk {
	return u.Update(func(s *UserGroupRateLimitWindowUpsert) {
		s.UpdateUsage5hUsd()
	})
}

// SetWindow5hStart sets the "window_5h_start" field.
func (u *UserGroupRateLimitWindowUpsertBulk) SetWindow5hStart(v time.Time) *UserGroupRateLimitWindowUpsertBulk {
	return u.Update(func(s *UserGroupRateLimitWindowUpsert) {
		s.SetWindow5hStart(v)
	})
}

// UpdateWindow5hStart sets the "window_5h_start" field to the value that was provided on create.
func (u *UserGroupRateLimitWindowUpsertBulk) UpdateWindow5hStart() *UserGroupRateLimitWindowUpsertBulk {
	return u.Update(func(s *UserGroupRateLimitWindowUpsert) {
		s.UpdateWindow5hStart()
	})
}

// ClearWindow5hStart clears the value of the "window_5h_start" field.
func (u *UserGroupRateLimitWindowUpsertBulk) ClearWindow5hStart() *UserGroupRateLimitWindowUpsertBulk {
	return u.Update(func(s *UserGroupRateLimitWindowUpsert) {
		s.ClearWindow5hStart()
	})
}

// Exec executes the query.
func (u *UserGroupRateLimitWindowUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserGroupRateLimitWindowCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserGroupRateLimitWindowCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserGroupRateLimitWindowUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
