// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usergroupratelimitwindow"
)

// UserGroupRateLimitWindowUpdate is the builder for updating UserGroupRateLimitWindow entities.
type UserGroupRateLimitWindowUpdate struct {
	config
	hooks    []Hook
	mutation *UserGroupRateLimitWindowMutation
}

// Where appends a list predicates to the UserGroupRateLimitWindowUpdate builder.
func (_u *UserGroupRateLimitWindowUpdate) Where(ps ...predicate.UserGroupRateLimitWindow) *UserGroupRateLimitWindowUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserGroupRateLimitWindowUpdate) SetUpdatedAt(v time.Time) *UserGroupRateLimitWindowUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UserGroupRateLimitWindowUpdate) SetDeletedAt(v time.Time) *UserGroupRateLimitWindowUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UserGroupRateLimitWindowUpdate) SetNillableDeletedAt(v *time.Time) *UserGroupRateLimitWindowUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UserGroupRateLimitWindowUpdate) ClearDeletedAt() *UserGroupRateLimitWindowUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserGroupRateLimitWindowUpdate) SetUserID(v int64) *UserGroupRateLimitWindowUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserGroupRateLimitWindowUpdate) SetNillableUserID(v *int64) *UserGroupRateLimitWindowUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *UserGroupRateLimitWindowUpdate) SetGroupID(v int64) *UserGroupRateLimitWindowUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *UserGroupRateLimitWindowUpdate) SetNillableGroupID(v *int64) *UserGroupRateLimitWindowUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetUsage5hUsd sets the "usage_5h_usd" field.
func (_u *UserGroupRateLimitWindowUpdate) SetUsage5hUsd(v float64) *UserGroupRateLimitWindowUpdate {
	_u.mutation.ResetUsage5hUsd()
	_u.mutation.SetUsage5hUsd(v)
	return _u
}

// SetNillableUsage5hUsd sets the "usage_5h_usd" field if the given value is not nil.
func (_u *UserGroupRateLimitWindowUpdate) SetNillableUsage5hUsd(v *float64) *UserGroupRateLimitWindowUpdate {
	if v != nil {
		_u.SetUsage5hUsd(*v)
	}
	return _u
}

// AddUsage5hUsd adds value to the "usage_5h_usd" field.
func (_u *UserGroupRateLimitWindowUpdate) AddUsage5hUsd(v float64) *UserGroupRateLimitWindowUpdate {
	_u.mutation.AddUsage5hUsd(v)
	return _u
}

// SetWindow5hStart sets the "window_5h_start" field.
func (_u *UserGroupRateLimitWindowUpdate) SetWindow5hStart(v time.Time) *UserGroupRateLimitWindowUpdate {
	_u.mutation.SetWindow5hStart(v)
	return _u
}

// SetNillableWindow5hStart sets the "window_5h_start" field if the given value is not nil.
func (_u *UserGroupRateLimitWindowUpdate) SetNillableWindow5hStart(v *time.Time) *UserGroupRateLimitWindowUpdate {
	if v != nil {
		_u.SetWindow5hStart(*v)
	}
	return _u
}

// ClearWindow5hStart clears the value of the "window_5h_start" field.
func (_u *UserGroupRateLimitWindowUpdate) ClearWindow5hStart() *UserGroupRateLimitWindowUpdate {
	_u.mutation.ClearWindow5hStart()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserGroupRateLimitWindowUpdate) SetUser(v *User) *UserGroupRateLimitWindowUpdate {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *UserGroupRateLimitWindowUpdate) SetGroup(v *Group) *UserGroupRateLimitWindowUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the UserGroupRateLimitWindowMutation object of the builder.
func (_u *UserGroupRateLimitWindowUpdate) Mutation() *UserGroupRateLimitWindowMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserGroupRateLimitWindowUpdate) ClearUser() *UserGroupRateLimitWindowUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *UserGroupRateLimitWindowUpdate) ClearGroup() *UserGroupRateLimitWindowUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserGroupRateLimitWindowUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserGroupRateLimitWindowUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserGroupRateLimitWindowUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserGroupRateLimitWindowUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserGroupRateLimitWindowUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if usergroupratelimitwindow.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized usergroupratelimitwindow.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := usergroupratelimitwindow.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserGroupRateLimitWindowUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserGroupRateLimitWindow.user"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserGroupRateLimitWindow.group"`)
	}
	return nil
}

func (_u *UserGroupRateLimitWindowUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usergroupratelimitwindow.Table, usergroupratelimitwindow.Columns, sqlgraph.NewFieldSpec(usergroupratelimitwindow.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usergroupratelimitwindow.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(usergroupratelimitwindow.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(usergroupratelimitwindow.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Usage5hUsd(); ok {
		_spec.SetField(usergroupratelimitwindow.FieldUsage5hUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUsage5hUsd(); ok {
		_spec.AddField(usergroupratelimitwindow.FieldUsage5hUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Window5hStart(); ok {
		_spec.SetField(usergroupratelimitwindow.FieldWindow5hStart, field.TypeTime, value)
	}
	if _u.mutation.Window5hStartCleared() {
		_spec.ClearField(usergroupratelimitwindow.FieldWindow5hStart, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usergroupratelimitwindow.UserTable,
			Columns: []string{usergroupratelimitwindow.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usergroupratelimitwindow.UserTable,
			Columns: []string{usergroupratelimitwindow.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usergroupratelimitwindow.GroupTable,
			Columns: []string{usergroupratelimitwindow.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usergroupratelimitwindow.GroupTable,
			Columns: []string{usergroupratelimitwindow.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usergroupratelimitwindow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserGroupRateLimitWindowUpdateOne is the builder for updating a single UserGroupRateLimitWindow entity.
type UserGroupRateLimitWindowUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserGroupRateLimitWindowMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserGroupRateLimitWindowUpdateOne) SetUpdatedAt(v time.Time) *UserGroupRateLimitWindowUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UserGroupRateLimitWindowUpdateOne) SetDeletedAt(v time.Time) *UserGroupRateLimitWindowUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UserGroupRateLimitWindowUpdateOne) SetNillableDeletedAt(v *time.Time) *UserGroupRateLimitWindowUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UserGroupRateLimitWindowUpdateOne) ClearDeletedAt() *UserGroupRateLimitWindowUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserGroupRateLimitWindowUpdateOne) SetUserID(v int64) *UserGroupRateLimitWindowUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserGroupRateLimitWindowUpdateOne) SetNillableUserID(v *int64) *UserGroupRateLimitWindowUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *UserGroupRateLimitWindowUpdateOne) SetGroupID(v int64) *UserGroupRateLimitWindowUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *UserGroupRateLimitWindowUpdateOne) SetNillableGroupID(v *int64) *UserGroupRateLimitWindowUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetUsage5hUsd sets the "usage_5h_usd" field.
func (_u *UserGroupRateLimitWindowUpdateOne) SetUsage5hUsd(v float64) *UserGroupRateLimitWindowUpdateOne {
	_u.mutation.ResetUsage5hUsd()
	_u.mutation.SetUsage5hUsd(v)
	return _u
}

// SetNillableUsage5hUsd sets the "usage_5h_usd" field if the given value is not nil.
func (_u *UserGroupRateLimitWindowUpdateOne) SetNillableUsage5hUsd(v *float64) *UserGroupRateLimitWindowUpdateOne {
	if v != nil {
		_u.SetUsage5hUsd(*v)
	}
	return _u
}

// AddUsage5hUsd adds value to the "usage_5h_usd" field.
func (_u *UserGroupRateLimitWindowUpdateOne) AddUsage5hUsd(v float64) *UserGroupRateLimitWindowUpdateOne {
	_u.mutation.AddUsage5hUsd(v)
	return _u
}

// SetWindow5hStart sets the "window_5h_start" field.
func (_u *UserGroupRateLimitWindowUpdateOne) SetWindow5hStart(v time.Time) *UserGroupRateLimitWindowUpdateOne {
	_u.mutation.SetWindow5hStart(v)
	return _u
}

// SetNillableWindow5hStart sets the "window_5h_start" field if the given value is not nil.
func (_u *UserGroupRateLimitWindowUpdateOne) SetNillableWindow5hStart(v *time.Time) *UserGroupRateLimitWindowUpdateOne {
	if v != nil {
		_u.SetWindow5hStart(*v)
	}
	return _u
}

// ClearWindow5hStart clears the value of the "window_5h_start" field.
func (_u *UserGroupRateLimitWindowUpdateOne) ClearWindow5hStart() *UserGroupRateLimitWindowUpdateOne {
	_u.mutation.ClearWindow5hStart()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserGroupRateLimitWindowUpdateOne) SetUser(v *User) *UserGroupRateLimitWindowUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *UserGroupRateLimitWindowUpdateOne) SetGroup(v *Group) *UserGroupRateLimitWindowUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the UserGroupRateLimitWindowMutation object of the builder.
func (_u *UserGroupRateLimitWindowUpdateOne) Mutation() *UserGroupRateLimitWindowMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserGroupRateLimitWindowUpdateOne) ClearUser() *UserGroupRateLimitWindowUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *UserGroupRateLimitWindowUpdateOne) ClearGroup() *UserGroupRateLimitWindowUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the UserGroupRateLimitWindowUpdate builder.
func (_u *UserGroupRateLimitWindowUpdateOne) Where(ps ...predicate.UserGroupRateLimitWindow) *UserGroupRateLimitWindowUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserGroupRateLimitWindowUpdateOne) Select(field string, fields ...string) *UserGroupRateLimitWindowUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserGroupRateLimitWindow entity.
func (_u *UserGroupRateLimitWindowUpdateOne) Save(ctx context.Context) (*UserGroupRateLimitWindow, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserGroupRateLimitWindowUpdateOne) SaveX(ctx context.Context) *UserGroupRateLimitWindow {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserGroupRateLimitWindowUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserGroupRateLimitWindowUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserGroupRateLimitWindowUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if usergroupratelimitwindow.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized usergroupratelimitwindow.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := usergroupratelimitwindow.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserGroupRateLimitWindowUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserGroupRateLimitWindow.user"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserGroupRateLimitWindow.group"`)
	}
	return nil
}

func (_u *UserGroupRateLimitWindowUpdateOne) sqlSave(ctx context.Context) (_node *UserGroupRateLimitWindow, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usergroupratelimitwindow.Table, usergroupratelimitwindow.Columns, sqlgraph.NewFieldSpec(usergroupratelimitwindow.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserGroupRateLimitWindow.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usergroupratelimitwindow.FieldID)
		for _, f := range fields {
			if !usergroupratelimitwindow.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usergroupratelimitwindow.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usergroupratelimitwindow.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(usergroupratelimitwindow.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(usergroupratelimitwindow.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Usage5hUsd(); ok {
		_spec.SetField(usergroupratelimitwindow.FieldUsage5hUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUsage5hUsd(); ok {
		_spec.AddField(usergroupratelimitwindow.FieldUsage5hUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Window5hStart(); ok {
		_spec.SetField(usergroupratelimitwindow.FieldWindow5hStart, field.TypeTime, value)
	}
	if _u.mutation.Window5hStartCleared() {
		_spec.ClearField(usergroupratelimitwindow.FieldWindow5hStart, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usergroupratelimitwindow.UserTable,
			Columns: []string{usergroupratelimitwindow.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usergroupratelimitwindow.UserTable,
			Columns: []string{usergroupratelimitwindow.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usergroupratelimitwindow.GroupTable,
			Columns: []string{usergroupratelimitwindow.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usergroupratelimitwindow.GroupTable,
			Columns: []string{usergroupratelimitwindow.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserGroupRateLimitWindow{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usergroupratelimitwindow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
