// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usergroupratelimitwindow"
)

// UserGroupRateLimitWindow is the model entity for the UserGroupRateLimitWindow schema.
type UserGroupRateLimitWindow struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// Used USD amount in the current 5-hour window
	Usage5hUsd float64 `json:"usage_5h_usd,omitempty"`
	// Start time of the current 5-hour window
	Window5hStart *time.Time `json:"window_5h_start,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserGroupRateLimitWindowQuery when eager-loading is set.
	Edges        UserGroupRateLimitWindowEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserGroupRateLimitWindowEdges holds the relations/edges for other nodes in the graph.
type UserGroupRateLimitWindowEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserGroupRateLimitWindowEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserGroupRateLimitWindowEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserGroupRateLimitWindow) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usergroupratelimitwindow.FieldUsage5hUsd:
			values[i] = new(sql.NullFloat64)
		case usergroupratelimitwindow.FieldID, usergroupratelimitwindow.FieldUserID, usergroupratelimitwindow.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case usergroupratelimitwindow.FieldCreatedAt, usergroupratelimitwindow.FieldUpdatedAt, usergroupratelimitwindow.FieldDeletedAt, usergroupratelimitwindow.FieldWindow5hStart:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserGroupRateLimitWindow fields.
func (_m *UserGroupRateLimitWindow) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usergroupratelimitwindow.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case usergroupratelimitwindow.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case usergroupratelimitwindow.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case usergroupratelimitwindow.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case usergroupratelimitwindow.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case usergroupratelimitwindow.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case usergroupratelimitwindow.FieldUsage5hUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field usage_5h_usd", values[i])
			} else if value.Valid {
				_m.Usage5hUsd = value.Float64
			}
		case usergroupratelimitwindow.FieldWindow5hStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field window_5h_start", values[i])
			} else if value.Valid {
				_m.Window5hStart = new(time.Time)
				*_m.Window5hStart = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserGroupRateLimitWindow.
// This includes values selected through modifiers, order, etc.
func (_m *UserGroupRateLimitWindow) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserGroupRateLimitWindow entity.
func (_m *UserGroupRateLimitWindow) QueryUser() *UserQuery {
	return NewUserGroupRateLimitWindowClient(_m.config).QueryUser(_m)
}

// QueryGroup queries the "group" edge of the UserGroupRateLimitWindow entity.
func (_m *UserGroupRateLimitWindow) QueryGroup() *GroupQuery {
	return NewUserGroupRateLimitWindowClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this UserGroupRateLimitWindow.
// Note that you need to call UserGroupRateLimitWindow.Unwrap() before calling this method if this UserGroupRateLimitWindow
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserGroupRateLimitWindow) Update() *UserGroupRateLimitWindowUpdateOne {
	return NewUserGroupRateLimitWindowClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserGroupRateLimitWindow entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserGroupRateLimitWindow) Unwrap() *UserGroupRateLimitWindow {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserGroupRateLimitWindow is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserGroupRateLimitWindow) String() string {
	var builder strings.Builder
	builder.WriteString("UserGroupRateLimitWindow(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("usage_5h_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.Usage5hUsd))
	builder.WriteString(", ")
	if v := _m.Window5hStart; v != nil {
		builder.WriteString("window_5h_start=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// UserGroupRateLimitWindows is a parsable slice of UserGroupRateLimitWindow.
type UserGroupRateLimitWindows []*UserGroupRateLimitWindow
