// Code generated by ent, DO NOT EDIT.

package projectprofilebinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the projectprofilebinding type in the database.
	Label = "project_profile_binding"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProjectProfileID holds the string denoting the project_profile_id field in the database.
	FieldProjectProfileID = "project_profile_id"
	// FieldResourceType holds the string denoting the resource_type field in the database.
	FieldResourceType = "resource_type"
	// FieldResourceID holds the string denoting the resource_id field in the database.
	FieldResourceID = "resource_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// EdgeProfile holds the string denoting the profile edge name in mutations.
	EdgeProfile = "profile"
	// Table holds the table name of the projectprofilebinding in the database.
	Table = "project_profile_bindings"
	// ProfileTable is the table that holds the profile relation/edge.
	ProfileTable = "project_profile_bindings"
	// ProfileInverseTable is the table name for the ProjectProfile entity.
	// It exists in this package in order to avoid circular dependency with the "projectprofile" package.
	ProfileInverseTable = "project_profiles"
	// ProfileColumn is the table column denoting the profile relation/edge.
	ProfileColumn = "project_profile_id"
)

// Columns holds all SQL columns for projectprofilebinding fields.
var Columns = []string{
	FieldID,
	FieldProjectProfileID,
	FieldResourceType,
	FieldResourceID,
	FieldCreatedAt,
	FieldMetadata,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ResourceTypeValidator is a validator for the "resource_type" field. It is called by the builders before save.
	ResourceTypeValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultMetadata holds the default value on creation for the "metadata" field.
	DefaultMetadata func() map[string]interface{}
)

// OrderOption defines the ordering options for the ProjectProfileBinding queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProjectProfileID orders the results by the project_profile_id field.
func ByProjectProfileID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectProfileID, opts...).ToFunc()
}

// ByResourceType orders the results by the resource_type field.
func ByResourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceType, opts...).ToFunc()
}

// ByResourceID orders the results by the resource_id field.
func ByResourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByProfileField orders the results by profile field.
func ByProfileField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProfileStep(), sql.OrderByField(field, opts...))
	}
}
func newProfileStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProfileInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProfileTable, ProfileColumn),
	)
}
