// Code generated by ent, DO NOT EDIT.

package projectprofilebinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldLTE(FieldID, id))
}

// ProjectProfileID applies equality check predicate on the "project_profile_id" field. It's identical to ProjectProfileIDEQ.
func ProjectProfileID(v int64) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldEQ(FieldProjectProfileID, v))
}

// ResourceType applies equality check predicate on the "resource_type" field. It's identical to ResourceTypeEQ.
func ResourceType(v string) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldEQ(FieldResourceType, v))
}

// ResourceID applies equality check predicate on the "resource_id" field. It's identical to ResourceIDEQ.
func ResourceID(v int64) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldEQ(FieldResourceID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// ProjectProfileIDEQ applies the EQ predicate on the "project_profile_id" field.
func ProjectProfileIDEQ(v int64) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldEQ(FieldProjectProfileID, v))
}

// ProjectProfileIDNEQ applies the NEQ predicate on the "project_profile_id" field.
func ProjectProfileIDNEQ(v int64) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldNEQ(FieldProjectProfileID, v))
}

// ProjectProfileIDIn applies the In predicate on the "project_profile_id" field.
func ProjectProfileIDIn(vs ...int64) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldIn(FieldProjectProfileID, vs...))
}

// ProjectProfileIDNotIn applies the NotIn predicate on the "project_profile_id" field.
func ProjectProfileIDNotIn(vs ...int64) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldNotIn(FieldProjectProfileID, vs...))
}

// ResourceTypeEQ applies the EQ predicate on the "resource_type" field.
func ResourceTypeEQ(v string) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldEQ(FieldResourceType, v))
}

// ResourceTypeNEQ applies the NEQ predicate on the "resource_type" field.
func ResourceTypeNEQ(v string) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldNEQ(FieldResourceType, v))
}

// ResourceTypeIn applies the In predicate on the "resource_type" field.
func ResourceTypeIn(vs ...string) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldIn(FieldResourceType, vs...))
}

// ResourceTypeNotIn applies the NotIn predicate on the "resource_type" field.
func ResourceTypeNotIn(vs ...string) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldNotIn(FieldResourceType, vs...))
}

// ResourceTypeGT applies the GT predicate on the "resource_type" field.
func ResourceTypeGT(v string) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldGT(FieldResourceType, v))
}

// ResourceTypeGTE applies the GTE predicate on the "resource_type" field.
func ResourceTypeGTE(v string) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldGTE(FieldResourceType, v))
}

// ResourceTypeLT applies the LT predicate on the "resource_type" field.
func ResourceTypeLT(v string) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldLT(FieldResourceType, v))
}

// ResourceTypeLTE applies the LTE predicate on the "resource_type" field.
func ResourceTypeLTE(v string) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldLTE(FieldResourceType, v))
}

// ResourceTypeContains applies the Contains predicate on the "resource_type" field.
func ResourceTypeContains(v string) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldContains(FieldResourceType, v))
}

// ResourceTypeHasPrefix applies the HasPrefix predicate on the "resource_type" field.
func ResourceTypeHasPrefix(v string) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldHasPrefix(FieldResourceType, v))
}

// ResourceTypeHasSuffix applies the HasSuffix predicate on the "resource_type" field.
func ResourceTypeHasSuffix(v string) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldHasSuffix(FieldResourceType, v))
}

// ResourceTypeEqualFold applies the EqualFold predicate on the "resource_type" field.
func ResourceTypeEqualFold(v string) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldEqualFold(FieldResourceType, v))
}

// ResourceTypeContainsFold applies the ContainsFold predicate on the "resource_type" field.
func ResourceTypeContainsFold(v string) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldContainsFold(FieldResourceType, v))
}

// ResourceIDEQ applies the EQ predicate on the "resource_id" field.
func ResourceIDEQ(v int64) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldEQ(FieldResourceID, v))
}

// ResourceIDNEQ applies the NEQ predicate on the "resource_id" field.
func ResourceIDNEQ(v int64) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldNEQ(FieldResourceID, v))
}

// ResourceIDIn applies the In predicate on the "resource_id" field.
func ResourceIDIn(vs ...int64) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldIn(FieldResourceID, vs...))
}

// ResourceIDNotIn applies the NotIn predicate on the "resource_id" field.
func ResourceIDNotIn(vs ...int64) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldNotIn(FieldResourceID, vs...))
}

// ResourceIDGT applies the GT predicate on the "resource_id" field.
func ResourceIDGT(v int64) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldGT(FieldResourceID, v))
}

// ResourceIDGTE applies the GTE predicate on the "resource_id" field.
func ResourceIDGTE(v int64) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldGTE(FieldResourceID, v))
}

// ResourceIDLT applies the LT predicate on the "resource_id" field.
func ResourceIDLT(v int64) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldLT(FieldResourceID, v))
}

// ResourceIDLTE applies the LTE predicate on the "resource_id" field.
func ResourceIDLTE(v int64) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldLTE(FieldResourceID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.FieldLTE(FieldCreatedAt, v))
}

// HasProfile applies the HasEdge predicate on the "profile" edge.
func HasProfile() predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProfileTable, ProfileColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProfileWith applies the HasEdge predicate on the "profile" edge with a given conditions (other predicates).
func HasProfileWith(preds ...predicate.ProjectProfile) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(func(s *sql.Selector) {
		step := newProfileStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProjectProfileBinding) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProjectProfileBinding) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProjectProfileBinding) predicate.ProjectProfileBinding {
	return predicate.ProjectProfileBinding(sql.NotPredicates(p))
}
