// Code generated by ent, DO NOT EDIT.

package usergroupratelimitwindow

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldEQ(FieldDeletedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldEQ(FieldUserID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldEQ(FieldGroupID, v))
}

// Usage5hUsd applies equality check predicate on the "usage_5h_usd" field. It's identical to Usage5hUsdEQ.
func Usage5hUsd(v float64) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldEQ(FieldUsage5hUsd, v))
}

// Window5hStart applies equality check predicate on the "window_5h_start" field. It's identical to Window5hStartEQ.
func Window5hStart(v time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldEQ(FieldWindow5hStart, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldNotNull(FieldDeletedAt))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldNotIn(FieldUserID, vs...))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldNotIn(FieldGroupID, vs...))
}

// Usage5hUsdEQ applies the EQ predicate on the "usage_5h_usd" field.
func Usage5hUsdEQ(v float64) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldEQ(FieldUsage5hUsd, v))
}

// Usage5hUsdNEQ applies the NEQ predicate on the "usage_5h_usd" field.
func Usage5hUsdNEQ(v float64) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldNEQ(FieldUsage5hUsd, v))
}

// Usage5hUsdIn applies the In predicate on the "usage_5h_usd" field.
func Usage5hUsdIn(vs ...float64) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldIn(FieldUsage5hUsd, vs...))
}

// Usage5hUsdNotIn applies the NotIn predicate on the "usage_5h_usd" field.
func Usage5hUsdNotIn(vs ...float64) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldNotIn(FieldUsage5hUsd, vs...))
}

// Usage5hUsdGT applies the GT predicate on the "usage_5h_usd" field.
func Usage5hUsdGT(v float64) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldGT(FieldUsage5hUsd, v))
}

// Usage5hUsdGTE applies the GTE predicate on the "usage_5h_usd" field.
func Usage5hUsdGTE(v float64) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldGTE(FieldUsage5hUsd, v))
}

// Usage5hUsdLT applies the LT predicate on the "usage_5h_usd" field.
func Usage5hUsdLT(v float64) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldLT(FieldUsage5hUsd, v))
}

// Usage5hUsdLTE applies the LTE predicate on the "usage_5h_usd" field.
func Usage5hUsdLTE(v float64) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldLTE(FieldUsage5hUsd, v))
}

// Window5hStartEQ applies the EQ predicate on the "window_5h_start" field.
func Window5hStartEQ(v time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldEQ(FieldWindow5hStart, v))
}

// Window5hStartNEQ applies the NEQ predicate on the "window_5h_start" field.
func Window5hStartNEQ(v time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldNEQ(FieldWindow5hStart, v))
}

// Window5hStartIn applies the In predicate on the "window_5h_start" field.
func Window5hStartIn(vs ...time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldIn(FieldWindow5hStart, vs...))
}

// Window5hStartNotIn applies the NotIn predicate on the "window_5h_start" field.
func Window5hStartNotIn(vs ...time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldNotIn(FieldWindow5hStart, vs...))
}

// Window5hStartGT applies the GT predicate on the "window_5h_start" field.
func Window5hStartGT(v time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldGT(FieldWindow5hStart, v))
}

// Window5hStartGTE applies the GTE predicate on the "window_5h_start" field.
func Window5hStartGTE(v time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldGTE(FieldWindow5hStart, v))
}

// Window5hStartLT applies the LT predicate on the "window_5h_start" field.
func Window5hStartLT(v time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldLT(FieldWindow5hStart, v))
}

// Window5hStartLTE applies the LTE predicate on the "window_5h_start" field.
func Window5hStartLTE(v time.Time) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldLTE(FieldWindow5hStart, v))
}

// Window5hStartIsNil applies the IsNil predicate on the "window_5h_start" field.
func Window5hStartIsNil() predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldIsNull(FieldWindow5hStart))
}

// Window5hStartNotNil applies the NotNil predicate on the "window_5h_start" field.
func Window5hStartNotNil() predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.FieldNotNull(FieldWindow5hStart))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserGroupRateLimitWindow) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserGroupRateLimitWindow) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserGroupRateLimitWindow) predicate.UserGroupRateLimitWindow {
	return predicate.UserGroupRateLimitWindow(sql.NotPredicates(p))
}
